trigger:
  branches:
    include:
      - master

pool: Adrian-PC

steps:
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
     
# Build and push the Docker image
- task: Docker@2
  inputs:
    containerRegistry: 'GoCheatContainerRegistry'
    repository: 'cicd_practice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure subscription 1(36ed3de6-9239-4dbf-92c7-9ec5f09a2323)'
    appName: 'CICDContainerPractice'
    resourceGroupName: 'GoCheat'
    containers: 'gocheatregistry.azurecr.io/cicd_practice:latest'